[build]
	command = "npm run build:full"
	publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

# Redirect all requests to index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
