volumes:
  prometheus_data: {}
  grafana_data: {}
  mongo_data: {}
  redis_data: {}

services:
  server:
    container_name: wordgrid-server
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
        reservations:
          memory: 256M
    build:
      context: ..
      dockerfile: server/Dockerfile
    restart: unless-stopped
    ports:
      - "8210:8210"
      - "8211:8211"
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:7-alpine
    container_name: wordgrid-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:7.0
    container_name: wordgrid-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: wordgrid-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "1256:1256"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.listen-address=:1256'
    depends_on:
      - server

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--docker_only=true'

  grafana:
    image: grafana/grafana:latest
    container_name: wordgrid-grafana
    restart: unless-stopped
    ports:
      - "4328:4328"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=4328
      - GF_SERVER_DOMAIN=192.168.1.199
      - GF_SERVER_ROOT_URL=http://192.168.1.199:4328/
