global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'wordgrid-server'
    metrics_path: '/health/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['wordgrid-server:8210']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:1256']
